route.ProductService.list=file
route.PaymentService.processPayment=db,file,email
route.OrderService.create=slackDigest,file

target.file.minLevel=DEBUG
target.file.async=false

target.db.minLevel=WARN
target.db.async=false
target.db.fallback=file

target.email.minLevel=ERROR
target.email.async=true

target.slackDigest.minLevel=ERROR
target.slackDigest.async=true
